### ISSUE TITLE
New Project Maintainer Wanted!

### ISSUE THREAD

**Issue by guy-keller** [guy-keller/jetty-runner#80]
Hello everyone,  

I am looking for someone to maintain this project.  

After **8+ YEARS** of working/maintaining it, I have decided that it is time for me to move on.  
If you are interested in taking over please let me know here.  

You will be added as a contributor and decide how this project will move forward.
In addition to that, you may choose to transfer the main repo elsewhere, change packages, etc.

To update the plugin you will also need to create a user on https://plugins.jetbrains.com/
So that you can upload a new version of the plugin ( zip ) when needed.

The only thing that I ask for is to keep it with the MIT license type.
My thanks go to those who have rated the plugin, helped here or elsewhere, or have used it!

Cheers, Gui

**Comment by amirtoole** [comment]
Hey @guikeller -- would be happy to take over maintenance of this project.

**Comment by guikeller** [comment]
Hi @amirtoole 

I have added you as a collaborator, if you could send me an e-mail that'd be great.
Need to share with you some of the details to publish the plugin.

Or did you want to publish it under a different name/package etc?

**Comment by guikeller** [comment]
Hi @amirtoole  

Are you still interested in maintaining the project ?  

The last step is to create a user on https://plugins.jetbrains.com  
So that you can upload a new version of the plugin when needed.  

Cheers

**Comment by guy-keller** [comment]
hi @jmcc0nn3ll - I have added you to the project as a collaborator; alternatively, I can transfer the ownership of the project to you so you can put the project under the 'jetty org' umbrella and you can put me as a collaborator, in case my interest in the project comes back. How does that sound to you?

**Comment by guy-keller** [comment]
hi @jmcc0nn3ll  

The Project has been updated! :smile:     
It is now written in Kotlin and uses the recommended way from JetBrains to build plugins (gradle).  

It was mainly migrated using IntelliJ's feature Java to Kotlin though.  
Hopefully, this will attract more attention to the project and people will want to contribute here.  

The bad news:   
I could not get the tests that were written in Java using PowerMock + Mockito to work/pass 
Some would not even 'initialise', and ended up on the too-hard basket, so yeah they are now all gone :disappointed: 

Cheers!

**Comment by jmcc0nn3ll** [comment]
Well you win some and you lose some!

Good news on our side as we finally have the Jetty repository setup on GitHub. The big repos are all in place but a lot of the smaller ones we haven't taken the time to get migrated and through the eclipse IP process for the ones that need it.

I hope I can make some time to work on this in the next few months; nice to see you got it updated!

**Comment by guy-keller** [comment]
Closing this, a very good contributor has been found.
